---
  - name: Install docker.io
    apt: name=docker.io state=present

  - name: kubernetes repository list
    apt_repository:
      repo: 'deb http://apt.kubernetes.io/  kubernetes-xenial   main'
      state: present
      filename: kubernetes.list
      update_cache: yes 

  - name: Add an Apt key
    apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present
  
  - name: Install kubeadm
    apt: 
      name: ['kubeadm=1.13.3-00', 'kubelet=1.13.3-00', 'kubectl=1.13.3-00']
      state: present

